fixup! enable deployment #9

diff --git a/.github/workflows/deploy-and-test-cluster.yml b/.github/workflows/deploy-and-test-cluster.yml
--- a/.github/workflows/deploy-and-test-cluster.yml
+++ b/.github/workflows/deploy-and-test-cluster.yml
@@ -84,14 +84,17 @@ jobs:
             exit 1
           fi
           
-          # Base64 encode the OPENAI_API_KEY
-          ENCODED_API_KEY=$(echo -n "$OPENAI_API_KEY" | base64 -w 0)
+          # Verify if OPENAI_API_KEY is base64 encoded
+          if ! echo "$OPENAI_API_KEY" | base64 -d > /dev/null 2>&1; then
+            echo "::error::OPENAI_API_KEY is not base64 encoded. Aborting deployment."
+            exit 1
+          fi
           
           # Install/upgrade the Helm chart
           echo "Deploying Application $APPLICATION_NAME: $APP_VERSION"
           helm upgrade --install $APPLICATION_NAME ./$APPLICATION_NAME \
           --set image.tag=${APP_VERSION} \
-          --set openai.apiKey="${{ secrets.OPENAI_API_KEY }}" \
+          --set openai.apiKey="${OPENAI_API_KEY}" \
           --namespace ${NAMESPACE} \
           --create-namespace \
           --cleanup-on-fail \
